export default {
  notfound: "/assets/images/404.svg",
  logo: "/vercel.svg",
  logo_img: "/assets/images/logo_img.png",
  story_img: "/assets/images/story_img.png",
  footerLogo: "/assets/images/footerLogo.png",
  brandLogo: "/assets/images/brandLogo.svg",
  bannerimg: "/assets/images/bannerimg.png",
  bannerCutout: "/assets/images/bannerCutout.png",
  banner_servicImg: "/assets/images/banner_servicImg.png",
  userimg1: "/assets/images/userimg1.png",
  shapeTestimoni1: "/assets/images/shapeTestimoni1.png",
  shapeLineImg1: "/assets/images/shapeLineImg1.png",
  yellowdots: "/assets/images/yellowdots.svg",
  ExportGradient: "/assets/images/ExportGradient.png",
  gradient_violate: "/assets/images/gradient_violate.png",
  whitedots: "/assets/images/whitedots.svg",
  callBackImg: "/assets/images/callBackImg.jpg",
  listImg1: "/assets/images/listImg1.png",
  listImg2: "/assets/images/listImg2.png",
  listImg3: "/assets/images/listImg3.png",
  listImg4: "/assets/images/listImg4.png",
  ticArrow: "/assets/images/ticArrow.svg",
  lineShape2: "/assets/images/lineShape2.png",
  shapeImgNew2: "/assets/images/shapeImgNew2.png"
};
